'use strict';
const KEY='camino-neurocirugia-v1';
const sections=['Panel principal','Sedes','Preparación','Investigación','Revisión semanal'];
const categories=['Habilidades quirúrgicas','Inglés médico','Investigación','CV','Entrevista'];
const states=['pendiente','en curso','completada'];
const priorities=['alta','media','baja'];
const uid=()=>crypto.randomUUID();
const initial=()=>({version:1,tasks:[],projects:[],reviews:[],sites:[['IMSS HGZ 45','R1 Cirugía General · primera opción'],['IMSS HGZ 110','R1 Cirugía General · segunda opción'],['CMNO','Neurocirugía'],['Hospital Civil Nuevo','Neurocirugía']].map(([name,option])=>({id:uid(),name,option,volume:'Por confirmar',neuro:'Por confirmar',requirements:'Por confirmar',referral:'Por confirmar'}))});
let data=initial(),page=0,filter='Todas',editing=null;
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const date=s=>s?new Date(s+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'}):'Sin fecha';
function valid(d){const text=(o,keys)=>keys.every(k=>typeof o[k]==='string'&&o[k].length<=10000);const dt=s=>s===''||(/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s);if(!d||d.version!==1)return false;return ['tasks','projects','reviews','sites'].every(k=>Array.isArray(d[k])&&d[k].length<=10000&&new Set(d[k].map(x=>x?.id)).size===d[k].length&&d[k].every(o=>o&&text(o,['id'])&&o.id&& (k==='sites'?text(o,['name','option','volume','neuro','requirements','referral']):k==='reviews'?text(o,['date','progress','obstacles','next'])&&dt(o.date):text(o,['title','date','priority','state',...(k==='tasks'?['category']:['next'])])&&dt(o.date)&&priorities.includes(o.priority)&&states.includes(o.state)&&(k!=='tasks'||categories.includes(o.category)))));}
try{const raw=localStorage.getItem(KEY);if(raw){const saved=JSON.parse(raw);if(!valid(saved))throw Error();data=saved}}catch{$('#notice').textContent='No se pudieron leer los datos guardados. Importa un respaldo si tienes uno. Los datos anteriores no se sobrescriben hasta que guardes un cambio.'}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(data));$('#notice').textContent='Cambios guardados.'}catch{$('#notice').textContent='No se pudo guardar en el navegador. Exporta un respaldo antes de cerrar.'}}
const actions=(kind,id)=>`<div class="row-actions"><button data-edit="${kind}" data-id="${escape(id)}">Editar</button><button class="danger" data-delete="${kind}" data-id="${escape(id)}">Eliminar</button></div>`;
function taskRow(t,i){return `<div class="task ${t.state==='completada'?'done':''}"><div>${i!==undefined?`<span class="priority-number">0${i+1}</span>`:''}<strong>${escape(t.title)}</strong><div class="meta">${escape(t.category)} · ${date(t.date)} · Prioridad ${t.priority} · <span class="badge">${t.state}</span>${t.date&&t.date<today()&&t.state!=='completada'?' · <span class="danger">Vencida</span>':''}</div></div>${actions('tasks',t.id)}</div>`}
function sorted(tasks){return [...tasks].sort((a,b)=>priorities.indexOf(a.priority)-priorities.indexOf(b.priority)||(a.date||'9999').localeCompare(b.date||'9999'))}
function render(){ $('nav').innerHTML=sections.map((s,i)=>`<button data-page="${i}" class="${page===i?'active':''}" ${page===i?'aria-current="page"':''}>${s}</button>`).join('');$('#heading').textContent=sections[page];$('#subtitle').textContent=['Tu meta, convertida en próximos pasos.','Compara tus opciones con información confirmada.','Construye las habilidades para tu siguiente etapa.','Cada proyecto avanza con una siguiente acción.','Haz una pausa, aprende y ajusta tu rumbo.'][page];let html='';const pending=data.tasks.filter(t=>t.state!=='completada');
if(page===0){const end=new Date(today()+'T12:00:00');end.setDate(end.getDate()+7);const limit=`${end.getFullYear()}-${String(end.getMonth()+1).padStart(2,'0')}-${String(end.getDate()).padStart(2,'0')}`;const weekly=sorted(pending.filter(t=>!t.date||t.date<=limit)).slice(0,3);const deadlines=[...pending.map(t=>({...t,kind:'Tarea'})),...data.projects.filter(p=>p.state!=='completada').map(p=>({...p,kind:'Proyecto'}))].filter(t=>t.date).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,6);html=`<div class="grid"><div class="card stat"><p>Tareas pendientes</p><strong>${pending.length}</strong></div><div class="card stat"><p>Tareas completadas</p><strong>${data.tasks.filter(t=>t.state==='completada').length}</strong></div><div class="card stat"><p>Proyectos activos</p><strong>${data.projects.filter(p=>p.state!=='completada').length}</strong></div></div><div class="card"><div class="section-top"><h2>Tres prioridades de la semana</h2><button class="primary" data-new="tasks">+ Nueva tarea</button></div><p class="note">Según prioridad y fecha, entre tareas sin fecha o con vencimiento en los próximos siete días, incluidas las vencidas.</p>${weekly.map(taskRow).join('')||'<div class="empty">Crea tu primera tarea para dar el siguiente paso.</div>'}</div><div class="card"><h2>Próximos vencimientos</h2>${deadlines.map(t=>`<div class="task"><div><strong>${escape(t.title)}</strong><div class="meta">${t.kind} · ${date(t.date)}${t.date<today()?' · Vencido':''}</div></div></div>`).join('')||'<p>No hay vencimientos registrados.</p>'}</div><div class="card"><h2>Tareas pendientes</h2>${sorted(pending).map(t=>taskRow(t)).join('')||'<p>No tienes tareas pendientes.</p>'}</div>`}
if(page===1)html=`<div class="section-top"><span class="badge">Información por verificar</span><button class="primary" data-new="sites">+ Añadir sede</button></div><div class="card"><p class="note">Las opciones iniciales reflejan tus preferencias. Confirma los datos con cada sede; no se presupone disponibilidad ni posibilidad de derivación.</p><div class="table-wrap"><table><thead><tr>${['Sede / opción','Volumen quirúrgico','Neurocirugía','Requisitos de ingreso','Derivación','Acciones'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${data.sites.map(s=>`<tr><td><strong>${escape(s.name)}</strong><p class="note">${escape(s.option)}</p></td>${['volume','neuro','requirements','referral'].map(k=>`<td>${escape(s[k])}</td>`).join('')}<td>${actions('sites',s.id)}</td></tr>`).join('')}</tbody></table></div></div>`;
if(page===2){const tasks=sorted(data.tasks.filter(t=>filter==='Todas'||t.category===filter));html=`<div class="section-top"><select class="filter" id="filter" aria-label="Filtrar por categoría">${['Todas',...categories].map(c=>`<option ${c===filter?'selected':''}>${c}</option>`).join('')}</select><button class="primary" data-new="tasks">+ Nueva tarea</button></div><div class="card">${tasks.map(t=>taskRow(t)).join('')||'<p>Crea una tarea de habilidades quirúrgicas, inglés médico, investigación, CV o entrevista.</p>'}</div>`}
if(page===3)html=`<div class="section-top"><p>De la idea a la siguiente acción.</p><button class="primary" data-new="projects">+ Nuevo proyecto</button></div>${data.projects.map(p=>`<article class="card"><div class="section-top"><h2>${escape(p.title)}</h2><span class="badge">${p.state}</span></div><p><strong>Siguiente acción:</strong> ${escape(p.next)||'Por definir'}</p><div class="task"><span class="meta">Fecha límite: ${date(p.date)} · Prioridad ${p.priority}</span>${actions('projects',p.id)}</div></article>`).join('')||'<div class="card empty">Registra un proyecto y define una acción pequeña para avanzar.</div>'}`;
if(page===4)html=`<div class="section-top"><p>Tu registro de progreso, semana a semana.</p><button class="primary" data-new="reviews">+ Nueva revisión</button></div>${[...data.reviews].sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<article class="card"><div class="section-top"><h2>Semana del ${date(r.date)}</h2>${actions('reviews',r.id)}</div>${[['progress','Qué avancé'],['obstacles','Qué obstáculos encontré'],['next','Qué haré la próxima semana']].map(([k,l])=>`<h3>${l}</h3><p class="review-text">${escape(r[k])||'Sin registrar'}</p>`).join('')}</article>`).join('')||'<div class="card empty">Dedica unos minutos a revisar tu semana y planear la siguiente.</div>'}`;
$('#content').innerHTML=html;}
const schemas={tasks:[['title','Título','text',true],['category','Área',categories],['date','Fecha','date'],['priority','Prioridad',priorities],['state','Estado',states]],projects:[['title','Proyecto','text',true],['next','Siguiente acción','textarea'],['date','Fecha límite','date'],['priority','Prioridad',priorities],['state','Estado',states]],sites:[['name','Nombre de la sede','text',true],['option','Opción / etapa','text'],['volume','Volumen quirúrgico','textarea'],['neuro','Presencia de Neurocirugía','text'],['requirements','Requisitos de ingreso','textarea'],['referral','Posibilidades de derivación','textarea']],reviews:[['date','Fecha de revisión','date',true],['progress','Qué avancé','textarea'],['obstacles','Qué obstáculos encontré','textarea'],['next','Qué haré la próxima semana','textarea']]};
function edit(kind,id){const item=id?data[kind].find(x=>x.id===id):{priority:'media',state:'pendiente',category:filter==='Todas'?categories[0]:filter,date:kind==='reviews'?today():'',volume:'Por confirmar',neuro:'Por confirmar',requirements:'Por confirmar',referral:'Por confirmar'};editing={kind,id};$('#dialog-title').textContent=(id?'Editar':'Crear')+' '+({tasks:'tarea',projects:'proyecto',sites:'sede',reviews:'revisión'}[kind]);$('#fields').innerHTML=schemas[kind].map(([k,label,type,required])=>`<label for="field-${k}">${label}</label>${Array.isArray(type)?`<select id="field-${k}" name="${k}">${type.map(v=>`<option ${item[k]===v?'selected':''}>${escape(v)}</option>`).join('')}</select>`:type==='textarea'?`<textarea id="field-${k}" name="${k}" maxlength="10000">${escape(item[k])}</textarea>`:`<input id="field-${k}" name="${k}" type="${type}" value="${escape(item[k])}" ${required?'required':''} ${type==='text'?'maxlength="500"':type==='date'?'min="1900-01-01" max="9999-12-31"':''}>`}`).join('');$('#editor').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page!==undefined){page=Number(b.dataset.page);render()}if(b.dataset.new)edit(b.dataset.new);if(b.dataset.edit)edit(b.dataset.edit,b.dataset.id);if(b.dataset.delete&&confirm('¿Eliminar este registro? Esta acción no se puede deshacer.')){data[b.dataset.delete]=data[b.dataset.delete].filter(x=>x.id!==b.dataset.id);persist();render()}});
$('#content').addEventListener('change',e=>{if(e.target.id==='filter'){filter=e.target.value;render()}});
$('#close').onclick=$('#cancel').onclick=()=>$('#editor').close();
$('#form').onsubmit=e=>{e.preventDefault();const {kind,id}=editing;const item={id:id||uid()};const fd=new FormData(e.target);for(const [k,,,required] of schemas[kind]){item[k]=String(fd.get(k)||'').trim();if(required&&!item[k]){$(`#field-${k}`).setCustomValidity('Completa este campo.');$(`#field-${k}`).reportValidity();$(`#field-${k}`).oninput=ev=>ev.target.setCustomValidity('');return}}const index=data[kind].findIndex(x=>x.id===id);if(index<0)data[kind].push(item);else data[kind][index]=item;persist();$('#editor').close();render()};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`camino-neurocirugia-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error();const imported=JSON.parse(await file.text());if(!valid(imported))throw Error();if(confirm('El respaldo reemplazará todos los datos actuales. Exporta primero si deseas conservarlos. ¿Continuar?')){data=imported;persist();render()}}catch{$('#notice').textContent='El archivo no es un respaldo válido de Camino a Neurocirugía. Tus datos no se modificaron.'}finally{e.target.value=''}};
render();
